---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
    use: media-fe
  name: jellyfin
  namespace: media
spec:
  selector:
    app: jellyfin
  clusterIP: None
  ports:
  - port: 8096
    name: jellyfin
---                                             # Load Balancer
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin-lb
  namespace: media
spec:
  ports:
  - port: 8096
    protocol: TCP
    targetPort: 8096
  selector:
    app: jellyfin
  type: LoadBalancer